### ISSUE TITLE
Can't load weights

### ISSUE THREAD

**Issue by habibagamal** [aub-mind/arabert#18] opened 2020-07-07 09:21 UTC
Hi, 
I am using tensorflow with transformers. 
That's the code I have so far. 

```
import tensorflow as tf
from transformers import AutoTokenizer, TFAutoModel

arabert_tokenizer = AutoTokenizer.from_pretrained("aubmindlab/bert-base-arabertv01",do_lower_case=False)
arabert_model = TFAutoModel.from_pretrained("aubmindlab/bert-base-arabertv01")
```

However, I get this error. 

OSError: Can't load weights for 'aubmindlab/bert-base-arabertv01'. Make sure that:

- 'aubmindlab/bert-base-arabertv01' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'aubmindlab/bert-base-arabertv01' is the correct path to a directory containing a file named one of tf_model.h5, pytorch_model.bin.

**Comment by WissamAntoun** [comment] 2020-07-07 10:54
Duplicate of #19

**Closed by WissamAntoun** 2020-07-07 10:54 UTC
