### ISSUE TITLE
ckpt file issue

### ISSUE THREAD

**Issue by rajae-Bens** [aub-mind/arabert#21] opened 2020-07-21 16:29 UTC
Hi,

I have an issue when i try to execute this code (araBERT_(Updated_Demo_TF).ipynb) on google colab 

InvalidArgumentError: From /job:worker/replica:0/task:0:
Unsuccessful TensorSliceReader constructor: Failed to get matching files on /content/drive/My Drive/tf_arabert/arabert_model.ckpt: Unimplemented: File system scheme '[local]' not implemented (file: '/content/drive/My Drive/tf_arabert/arabert_model.ckpt')
	 [[{{node checkpoint_initializer_180}}]]

Please could someone help?
Thank you

**Comment by WissamAntoun** [comment] 2020-07-21 17:14
Are you using TPUs?

**Comment by WissamAntoun** [comment] 2020-07-24 10:56
duplicate of #7

**Closed by WissamAntoun** 2020-07-24 10:56 UTC
